name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        node: [12]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies, build, and test the library
        run: |
          yarn
          yarn prepack
